config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
  sessions:      'companies/sessions',
  passwords:     'companies/passwords',
  registrations: 'companies/registrations'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }
  root "offers#index"
  resources :offers, only:[:index, :new, :create, :show] do
    resources :applies, only:[:create]
  end
  resources :users, only:[:show]
  resources :companies, only: [:show]
  resources :gcals, only: [:index]
  get 'events', to: 'events#events'
  post 'events/create', to: 'events#create'
  post 'events/update', to: 'events#update'
end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :company
  has_many :applies
  has_many :users, through: :applies
  validates :company_id, presence: true
  validates :title, presence: true
  validates :image, presence: true
  validates :job, presence: true
  validates :what, presence: true
  validates :why, presence: true
  validates :how, presence: true
  validates :thing, presence: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @offers = Offer.all.order("created_at DESC")
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      redirect_to offers_path, notice: '投稿が完了しました'
    else
      flash.now[:alert] = '投稿に失敗しました。必須項目を入力の上、投稿してください。'
      render :new
    end
  end

  def show
    @offer = Offer.find(params[:id])
    if user_signed_in?
      @user = current_user.id
    elsif company_signed_in?
      @company = current_company.id
    end
  end

  def offer_params
    params.require(:offer).permit(:title, :image, :job, :what, :why, :how, :thing).merge(company_id: current_company.id)
  end
end

app/views/offers/_company_header.html.haml
.header
  .header__logo
    = link_to image_tag("https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg"), offers_path
  .header__menu
    %ul
      %li
        = link_to "投稿する", new_offer_path
      %li
        %a{href: ""} フィードをみる
      %li
        %a{href: ""} プロフィール
      %li
        %a{href: ""} ツール
  .header__search
    %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
      %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
  .header__icon
    %i.fa.fa-search

  .header__profile
    =image_tag "company.jpg"
    #modal-overlay
      .hidden-menu
        .hidden-menu__account
          %ul
            %li
              %a.account-link
                .name-area
                  .name-profile
                    = current_company.company_name
                  .name-edit プロフィール編集
        .hidden-menu__visit
          %ul
            %li
              =link_to "募集した求人", company_path(current_company.id), class: "apply-visit"
            %li
              %a.apply-visit{:href => "/"} 保存したユーザー
        .hidden-menu__user
          %ul
            %li
              %a.user-menu{:href => "/"} フォローしている会社
            %li
              %a.user-menu{:href => "/"}友達を招待
            %li
              %a.user-menu{:href => "/"}アカウント設定
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'user-menu'
  .header__status
    %ul
      %li
        %a{href: ""}
          %i.fa.fa-commenting-o
      %li
        %a{href: ""}
          %i.fa.fa-user-o
      %li
        %a{href: ""}
          %i.fa.fa-bell

app/views/offers/_footer_index.html.haml
.footer
  .footer__contents
    .footer__contents__left-contents
      .footer__contents__left-contents__company-info
        %h4 About
        %ul
          %li 東京
          %li 大阪
          %li 沖縄
          %li samplesamplesample
      .footer__contents__left-contents__company-products
        .footer__contents__left-contents__company-products__left
          %h4 Products
          %ul
            %li 東京
            %li 大阪
            %li 沖縄
            %li samplesamplesample
        .footer__contents__left-contents__company-products__right
          %ul
            %li 東京
            %li 大阪
            %li 沖縄
            %li samplesamplesample
      .footer__contents__left-contents__company-logo
        =image_tag "footer-logo-wantedly.png"
    .footer__contents__right-contents
      .footer__contents__right-contents__lang
        %h4 Langages
        %ul
          %li 英語
          %li 日本語
      .footer__contents__right-contents__message
        %input#text{:name => "message",:placeholder => "wantedlyに意見を送る"}
      .footer__contents__right-contents__send
        %input#send{:type => "submit",:value => "送信"}

app/views/offers/_index.html.haml
!!!

- if company_signed_in?
  = render '/offers/company_header'
- else user_signed_in?
  = render '/offers/user_header'

.contents.slider
  - @offers.shuffle.first(5).each do |offer|
    .contents__box
      .main-contents
        .main-contents__company.img-block
          = link_to "/offers/#{offer.id}" do
            %span
              = image_tag(offer.image) if offer.image
        .main-contents__details
          .main-contents__details__job
            = offer.job
          %h2.main-contents__details__title
            = link_to "/offers/#{offer.id}" do
              %span
                = offer.title
          %p.main-contents__details__name
            %img.icon{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
            %a{href: ""} 
              = offer.company.company_name
          .main-contents__details__like
            %a{href: ""}
              %i.fa.fa-bullhorn
.slick-dots

.recruitment-contents
  .recruitment-contents__center
    .recruitment-contents__center__left
      .recruitment-contents__center__left__inner
        .recruitment-contents__center__left__inner__menu
          .menu-header
            %h4 検索条件
          .menu-contents
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "エンジニア", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "中途採用", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "地域や特徴などの条件を追加", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-word
              %ul
                %li 秘書
                %li アニメ
                %li ブライダル
                %li コンサルタント
            .job-region
              %h5 地域
              %ul
                %li 東京
                %li 大阪
                %li 沖縄
                %li 北海道
            .job-characteristics
              %h5 特徴
              %ul
                %li TechCrunchに掲載実績あり
                %li 海外進出している
                %li 1億円以上の資金を調達済み
                %li Wantedlyに初登場

    .recruitment-contents__center__main
      .recruitment-contents__center__main__menu
        .recruitment-count 
          %p 10/2509
        .recruitment-status
          %ul 
            %li
              %p 並べ替え
            %li
              %a{href: ""} おすすめ
            %li
              %a{href: ""} 新着
            %li
              %a{href: ""} 人気
      .recruitment-contents__center__main__area
        - @offers.each do |offer|
          .recruitment-contents__center__main__area__company
            = link_to "/offers/#{offer.id}" do
              %span
                = image_tag(offer.image) if offer.image
            .recruitment-contents__center__main__area__details
              .recruitment-contents__center__main__area__details__job
                = offer.job
              %h2.recruitment-contents__center__main__area__details__title
                = link_to "/offers/#{offer.id}" do
                  %span
                    = offer.title
              %p.recruitment-contents__center__main__area__details__message
                = link_to "/offers/#{offer.id}" do
                  %span
                    = offer.thing
              .recruitment-contents__center__main__area__details__name
                .recruitment-contents__center__main__area__details__name__icon
                  %a{href: ""}
                    %img.icon{:alt => "Wantedly", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg",}/
                %p.recruitment-contents__center__main__area__details__name__text
                  %a{href: ""}
                    = offer.company.company_name
                .recruitment-contents__center__main__area__details__name__like
                  %a{href: ""}
                    %i.fa.fa-bullhorn

= render '/offers/footer_index'

app/views/offers/_user_header.html.haml
.header
  .header__logo
    = link_to image_tag("https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg"), offers_path
  .header__menu
    %ul
      %li
        %a{href: ""} 募集を見る
      %li
        %a{href: ""} フィードをみる
      %li
        %a{href: ""} プロフィール
      %li
        %a{href: ""} ツール
  .header__search
    %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
      %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
  .header__icon
    %i.fa.fa-search

  .header__profile
    =image_tag "man.png"
    #modal-overlay
      .hidden-menu
        .hidden-menu__account
          %ul
            %li
              %a.account-link
                .name-area
                  .name-profile
                    = current_user.name
                  .name-edit プロフィール編集
        .hidden-menu__visit
          %ul
            %li
              =link_to "応募した企業", user_path(current_user.id), class: "apply-visit"
            %li
              %a.apply-visit{:href => "/"} 保存した募集
        .hidden-menu__user
          %ul
            %li
              %a.user-menu{:href => "/"} フォローしている会社
            %li
              %a.user-menu{:href => "/"}友達を招待
            %li
              %a.user-menu{:href => "/"}アカウント設定
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'user-menu'
  .header__status
    %ul
      %li
        = link_to gcals_path(current_user.id) do
          %i.fa.fa-calendar-o
      %li
        %a{href: ""}
          %i.fa.fa-commenting-o
      %li
        %a{href: ""}
          %i.fa.fa-user-o
      %li
        %a{href: ""}
          %i.fa.fa-bell

app/views/offers/index.html.haml
!!!

- if company_signed_in?
  = render '/offers/index'
- elsif user_signed_in?
  = render '/offers/index'
- else
  #modalrogIn-bg
  .top-contents
    .header
      .header__logo
        %a{href: ""}
          =image_tag "footer-logo-wantedly.png"
      .header__menu
        .header__menu__right
          %ul
            %li
              %p iOS/Android アプリ
            %li
              %a{href: ""} 
                %img.icon{:alt => "Wantedly", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg",}/
            %li
              %a{href: ""} 
                %img.icon{:alt => "Wantedly", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg",}/
        .header__menu__left
          %ul
            %li
              .rogIn ログイン
              #modal-rogIn
                .rogIn-menu
                  .close &times;
                  .hidden-menu__signIn
                    %ul
                      %li
                        = link_to "ユーザー", new_user_session_path, class: 'user-menu'
                      %li
                        = link_to "採用担当者の方", new_company_session_path, class: 'user-menu'
            %li
              = link_to new_company_registration_path do 
                採用担当者の方(新規登録)
    .messages
      .messages__center
        .messages__center__top
          %h1「働くを面白く」
        .messages__center__middle
          %p 月間150万人が利用する、国内最大のビジネス SNS
        .messages__center__bottom
          .messages__center__bottom__SNS
            %a{href: ""}
              .square_btn Facebookで今すぐログイン
          .messages__center__bottom__Email
            = link_to new_user_registration_path do
              .square_btn Emailで登録

app/views/offers/new.html.haml
!!!

= render '/offers/company_header'

= form_for @offer do |f|
  .post-main
    .post-main__bar
      .post-main__bar__inner
        .post-main__bar__inner__section
          %ul
            %li.postArticle 新規募集作成
            #modalPost-content.post-menu
              .close &times;
              .post-menu__header
                %ul#tabs
                  %li.step1 会社情報の入力
              .post-menu__job
                .post-menu__job__form
                  .field-label
                    = f.label "職種"
                  .field-select
                    = f.text_field :job, placeholder: :職種を入力してください
                .post-menu__job__title
                  .field-label
                    = f.label "タイトル"
                    %abbr (必須)
                  .field-text
                    = f.text_field :title, placeholder: :ユーザー6万人の人材サイトに喝を入れるwebデザイナー募集
              .post-menu__job__detail
                .post-menu__job__detail__form
                  .field-label
                    = f.label "何をやっているのか"
                    %abbr (必須)
                  .field-detail
                    = f.text_field :what, placeholder: :募集要項の詳細を入力して下さい
                  .field-label
                    = f.label "なぜやっているのか"
                    %abbr (必須)
                  .field-detail
                    = f.text_field :why, placeholder: :募集要項の詳細を入力して下さい
                  .field-label
                    = f.label "どうやっているのか"
                    %abbr (必須)
                  .field-detail
                    = f.text_field :how, placeholder: :募集要項の詳細を入力して下さい
                  .field-label
                    = f.label "こんなことをやります"
                    %abbr (必須)
                  .field-detail
                    = f.text_field :thing, placeholder: :募集要項の詳細を入力して下さい
                .post-menu__job__image
                  .post-menu__job__image__form
                    %p 会社イメージ(必須)
                    .field-label
                      = f.label :image do
                        #icon
                          = f.file_field :image, class: "field-image"
                        %i.fa.fa-picture-o
                .post-menu__job__bottom
                  = f.submit "投稿する", class: "send-btn"
            %a{:href => "/"}
            %li.item ダッシュボード
            %li.item 募集
            %li.item フィード
            %li.item アナリティクス
            %li.item 候補者
            %li.item メッセージ
    .post-main__right
      #modalPost-bg.post-main__right__inner

app/views/offers/show.html.haml
!!!
#modalApply-bg
  .close &times;
  #modal-rogIn
    .apply-menu
      .apply-menu__inner
        .apply-menu__inner__title
          あなたが興味を持っていることを担当者に伝えます。
        .apply-menu__inner__contents
          .apply-menu__inner__contents__explanation
            %p どれくらい興味があるのか教えてください。
          .apply-menu__inner__contents__select
            .apply-menu__inner__contents__select__comment
              .apply-menu__inner__contents__select__comment__label
                %input{:name => "q1", :type => "radio", :value => "今すぐ一緒に働きたい"}今すぐ一緒に働きたい
              .apply-menu__inner__contents__select__comment__label
                %input{:name => "q1", :type => "radio", :value => "まずは話を聞いてみたい"}まずは話を聞いてみたい
              .apply-menu__inner__contents__select__comment__label
                %input{:name => "q1", :type => "radio", :value => "少しだけ興味があります"}少しだけ興味があります
          .apply-menu__inner__contents__submit
            .entry
              .entry__button
                =link_to "今すぐエントリー", offer_applies_path(@offer), method: :post

- if company_signed_in?
  = render '/offers/company_header'
- else user_signed_in?
  = render '/offers/user_header'

.show-contents
  .show-contents__main
    .show-contents__main__inner
      .show-contents__main__inner__head
        .show-contents__main__inner__head__top
          .show-contents__main__inner__head__top__job
            = @offer.job
          .show-contents__main__inner__head__top__title
            = @offer.title
          .show-contents__main__inner__head__top__name
            .show-contents__main__inner__head__top__name__icon
              %a{href: ""}
                %img.icon{:alt => "Wantedly", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg",}/
            .show-contents__main__inner__head__top__name__text
              = @offer.company.company_name
        .show-contents__main__inner__head__cover
          = image_tag(@offer.image) if @offer.image
      .show-contents__main__inner__body
        .show-contents__main__inner__body__column
          .show-contents__main__inner__body__column__inner
            .show-contents__main__inner__body__column__inner__what
              %h3 なにをやっているのか
              %p
                = @offer.what
            .show-contents__main__inner__body__column__inner__why
              %h3 なぜやるのか
              %p
                = @offer.why
            .show-contents__main__inner__body__column__inner__how
              %h3 どうやっているのか
              %p
                = @offer.how
            .show-contents__main__inner__body__column__inner__thing
              %h3 こんなことをやります
              %p
                = @offer.thing
        .show-contents__main__inner__body__sidebar
          .show-contents__main__inner__body__sidebar__inner
            .show-contents__main__inner__body__sidebar__inner__action
              - if current_user
                .show-contents__main__inner__body__sidebar__inner__action__btn
                  .entry-btn.btn 話を聞きに行きたい
                .show-contents__main__inner__body__sidebar__inner__action__text
                  %p.count 現在10人が応募しています。
                  %p 応募状況は、他のユーザーに公開されません。
                  %p さらに詳しく
                .show-contents__main__inner__body__sidebar__inner__action__later
                  .later-btn
                    = link_to "あとで見る","", class:'later'
        .show-contents__main__inner__body__suggest
          .show-contents__main__inner__body__suggest__inner
  .show-contents__outer
    .show-contents__outer__suggest

= render '/offers/footer_index'